#!/bin/sh

set -eu
VERSION="0.0.1"
SCRIPT_NAME=$(basename "$0")

readlinkf() {
    [ "${1:-}" ] || return 1
    max_symlinks=40
    CDPATH='' # to avoid changing to an unexpected directory

    target=$1
    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
    [ -d "${target:-/}" ] && target="$target/"

    cd -P . 2>/dev/null || return 1
    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
        if [ ! "$target" = "${target%/*}" ]; then
            case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
            esac
            target=${target##*/}
        fi

        if [ ! -L "$target" ]; then
            target="${PWD%/}${target:+/}${target}"
            printf '%s\n' "${target:-/}"
            return 0
        fi
        link=$(ls -dl -- "$target" 2>/dev/null) || break
        target=${link#*" $target -> "}
    done
    return 1
}

self=$(readlinkf "$0")
script_dir=${self%/*}
# script_dir="/usr/share/teffects"

# Set variables
VAR1="VAR1."
VAR2="VAR2."
VAR3="VAR3."

# Import files
# shellcheck disable=SC1091
{
    . "${script_dir}/lib/getoptions.sh"
    . "${script_dir}/lib/main_definition.sh"
    . "${script_dir}/lib/utils.sh"
    . "${script_dir}/lib/cmd1_definition.sh"
    . "${script_dir}/lib/cmd2_definition.sh"
    # more files
}

# Keep it. You need this for main parser.
eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

# If you need to check OS uncomment it
# if [ "$(uname)" = "Linux" ]; then
#     echo "Your OS is Linux."
# elif [ "$(uname)" = "Darwin" ]; then
#     echo "Your OS is mac."
# fi

# If you are using Bash, check Bash version
# if ((BASH_VERSINFO[0] < 5)); then
#     printf '%s\n' "Error: This requires Bash v5.0 or higher. You have version $BASH_VERSION." 1>&2
#     exit 2
# fi

# Check dependencies of your script
# check_cmd jq
# check_cmd you_dont_have_it

# color check
blackprint "Testing black print."
blueprint "Testing blue print."
cyanprint "Testing cyan print."
defaultprint "Testing default print."
greenprint "Testing green print."
magentaprint "Testing magenta print."
redprint "Testing red print."
whiteprint "Testing white print."
yellowprint "Testing yellow print."

# Add more commands.
# Don't forget to add your command in lib/main_definition.sh
if [ $# -gt 0 ]; then
    cmd=$1
    shift
    case $cmd in
    cmd1)
        eval "$(getoptions parser_definition_cmd1 parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/cmd1.sh"
        fn_cmd1 "$@"
        ;;
    cmd2)
        eval "$(getoptions parser_definition_cmd2 parse "$0")"
        parse "$@"
        eval "set -- $REST"
        # shellcheck disable=SC1091
        . "${script_dir}/src/cmd2.sh"
        fn_cmd2 "$@"
        ;;
    # more lines
    --) ;; # no subcommand, arguments only
    esac
fi
